### PR TITLE
fixed the blog link

### PR DESCRIPTION
**Pull request by robregan**
When you clicked the user's website, it took you to `https://https://{website}` 

Also, if a users website started with just `www` then it would crash/stay loading. Added a regex test and reassigned `blog` if it fails, but I'm not sure if this is the best way to go about it. Seems to work great for now!  ヾ(⌐■_■)ノ♪

### CODE REVIEW

**Comment by bushblade** [comment]
Hi @robregan 
Thanks for the PR, however this has been fixed in [66c9157](https://github.com/bradtraversy/github-finder-app/commit/66c915749fdb3061db8b5b3d21601de72ebe9a66) with notes for students added to the README.

**Comment by robregan** [comment]
Ah ok! @bushblade, ty! It was super helpful to see the commit you linked. I am still learning and trying to do small PR's to add to my experience, but maybe next time I should check out the readme file (all of it!) first lmao.

**Comment by bushblade** [comment]
No to be fair it was a good PR, and I only pushed the fix this evening.
Just with it being course code we need to make it easy for students to adopt the changes, so needs documenting and notes where possible.

**Comment by robregan** [comment]
Ah ok great! Makes sense. Documentation/notes/better-README-files are things that I am currently working on improving, so thanks again for all your help!

**Pull request closed without merging**
